name: sweetyai_learning_assistant
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter: # CRITICAL: Required for every Flutter project - DO NOT REMOVE
    sdk: flutter # CRITICAL: Required for every Flutter project - DO NOT REMOVE

  # CRITICAL: Core UI and responsive design - DO NOT REMOVE OR MODIFY
  sizer: ^2.0.15 # Required for responsive design system
  flutter_svg: ^2.0.9 # Required for SVG icon support
  google_fonts: ^6.1.0 # Required for typography (replaces local fonts)
  shared_preferences: ^2.2.2 # Required for local data storage
  web: ^1.1.1

  # Feature dependencies - safe to modify
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.4.0
  fluttertoast: ^8.2.4
  fl_chart: ^0.65.0
  http: ^1.1.0
  record: ^6.0.0
  permission_handler: ^11.1.0
  audio_waveforms: ^1.3.0
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.5
  video_player: ^2.10.0
  flutter_code_editor: ^0.3.4
  table_calendar: ^3.0.9
  provider: ^6.1.1
  flutter_riverpod: ^2.4.9

  webview_flutter: ^4.13.0
  local_auth: ^2.1.6
  local_auth_android: ^1.0.34
  local_auth_ios: ^1.1.6
  web_socket_channel: ^3.0.3
  lottie: ^3.3.1

dev_dependencies:
  flutter_test: # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
    sdk: flutter # CRITICAL: Required for Flutter project testing - DO NOT REMOVE
  flutter_lints: ^5.0.0 # CRITICAL: Required for code quality - DO NOT REMOVE

flutter:
  uses-material-design: true # CRITICAL: Required for Material icon font - DO NOT REMOVE
  assets:
    - assets/
    - assets/images/
    - assets/crex/
    - env.json
